super-dubu/super-dubu-FE

- .gitignore
- package-lock.json
- package.json
- src/components/Guest/GuestBook.jsx
- src/components/Guest/GuestHeader.jsx
- src/components/Guest/GuestSell.jsx
Guest Booking 과정 중 Success Modal / Date Modal 창 구현
Guest Booking input 받는 형식 구현
Guest Sell Page Image 이상하게 처리되는거 디버깅
Guest Header 중개사 Login 버튼 디버깅
> [Chore] GuestSell / GuestHeader / GuestBook 수정

- src/App.jsx
- src/components/Member/MemberJoin.jsx
- src/components/Member/MemberLogin.jsx
- id 중복오류, 비밀번호 확인 로직 등은 아직 구현하지 않았음
- 회원가입 완료 시 본인 인증 창으로 넘어가도록 수정할 것 -> 일단 회원가입 완료 후 login 창으로 넘어가도록 구현하였음
- 회원가입 완료 시 alert창으로 회원가입이 완료되었음을 알림
> [Add] MemberJoin 구현

- src/App.jsx
- src/components/Member/Contract/Contract1.jsx
- src/components/Member/MemberJoin.jsx
- src/components/Member/UploadProperty.jsx
- src/components/Member/UploadPropertyDetail.jsx
- UploadProperty.jsx , UploadPropertyDetail.jsx 두 파일로 나누어서 작업 예정
- 인터페이스 구현 완료
- 사진 업로드 및 미리보기
- Backend API와의 연동 및 데이터 전송
> [Chore] UploadProperty 수정

- src/components/Guest/GuestBook.jsx
- src/components/Guest/GuestInfo.jsx
- src/components/Guest/GuestMain.jsx
- src/components/Guest/GuestSell.jsx
[Chore] GuestBook json 파일로 넘기기 / GuestSell Data Filtering
> [Chore] GuestBook json 파일로 넘기기 / GuestSell Data Filtering

- package-lock.json
- package.json
- src/components/Guest/GuestInfo.jsx
- src/components/Guest/GuestSell.jsx
- src/components/Member/MemberHeader.jsx
- src/components/Member/MemberJoin.jsx
- src/components/Member/MemberLogin.jsx
- src/components/api/axios-instance.js
- src/hooks/GetData.js
- vite.config.js
[Chore] 회원가입 구현 / 포트번호 변경 / GuestSell 리팩토링 / 로그인 구현중
> [Chore] 회원가입 구현 / 포트번호 변경 / Guest Sell 리팩토링 / 로그인 구현중

- src/components/Member/MemberLogin.jsx
- src/components/Member/MemberMain.jsx
> [Chore] MemberInfo 받아오기

- src/App.jsx
- src/components/Guest/GuestHeader.jsx
- src/components/Member/MemberHeader.jsx
- src/components/Member/MemberLogin.jsx
- src/components/Member/MemberMain.jsx
- src/components/api/AuthContext.jsx
> [Chore] Member Context API 작업

- src/components/Guest/GuestBook.jsx
- src/components/Guest/GuestInfo.jsx
- src/components/Guest/GuestMain.jsx
- src/components/Guest/GuestSell.jsx
- src/components/Member/UploadProperty.jsx
[Chore] ItemInfo 데이터 받아오기 및 Post 구현
+
[Chore] ItemInfo로 GuestSell, GuestInfo 수정
> [Chore] ItemInfo 데이터 받아오기 및 Post 구현

- src/components/Guest/GuestBook.jsx
- src/components/Guest/GuestSell.jsx
- src/components/Member/MemberHeader.jsx
- src/components/Member/MemberJoin.jsx
- src/components/Member/MemberLogin.jsx
- src/components/Member/MemberMain.jsx
- src/components/Member/MemberMypage.jsx
- src/components/Member/MemberSide.jsx
- src/components/Member/UploadProperty.jsx
- src/hooks/GetData.js
> [Chore] 전체적인 REST API 안정화

- package-lock.json
- package.json
- src/App.jsx
- src/components/Guest/GuestInfo.jsx
- src/components/Guest/GuestSell.jsx
- src/components/Member/AdminHoliday.jsx
- src/components/Member/AdminWorkHours.jsx
- src/components/Member/BookAdmin.jsx
- src/components/Member/Contract/Contract1.jsx
- src/components/Member/Contract/Contract2.jsx
- src/components/Member/Contract/Contract3.jsx
- src/components/Member/Contract/Contract4.jsx
- src/components/Member/Contract/Contract5.jsx
- src/components/Member/Contract/Contract6.jsx
- src/components/Member/MemberMain.jsx
- src/components/Member/MemberMypage.jsx
- src/components/Member/MemberSide.jsx
- src/components/Member/UploadPropertyDetail.jsx
- src/components/api/KakaoMap.jsx
- yarn.lock
[Chore] KMap 마커 수정 및 GuestSell 리팩토링
> [Chore] KMap 마커 수정 및 GuestSell 리팩토링

- src/App.jsx
- src/components/Guest/GuestBook.jsx
- src/components/Guest/GuestInfo.jsx
- src/components/Guest/GuestMain.jsx
- src/components/Guest/GuestSell.jsx
- src/components/Member/MemberMain.jsx
- src/components/api/KakaoMap.jsx
- src/components/api/MobileAuth.jsx
- src/components/api/Toss/Success.jsx
[Chore] GuestSell Page 리팩토링 및 Filtering 수정 / Kakao MAP marker 설정, GuestBook 리팩토링
> [Chore] GuestSell Page 리팩토링 및 Filtering 수정 / Kakao MAP marker 설정, GuestBook 리팩토링

- src/App.jsx
- src/components/Member/Contract/Contract1.jsx
- src/components/Member/Contract/Contract6.jsx
- src/components/Member/Contract/MobileAuth.jsx
- src/components/Member/MemberMain.jsx
- src/components/Member/MemberMypage.jsx
- src/components/api/MobileAuth.jsx
모바일 인증 화면 구현 및 임대인, 임차인 휴대폰 번호 입력 받아서 ItemLog에 저장
> [Chore] Contract1에서 임대인, 임차인 휴대폰 번호 입력받아서 itemLog에 저장

- src/App.jsx
- src/components/Member/Contract/Contract1.jsx
- src/components/Member/Contract/Contract6.jsx
- src/components/Member/MemberMypage.jsx
- src/components/api/MobileAuth.jsx
- src/components/api/Toss/Success.jsx
- src/components/api/Toss/TossPayment.jsx
[Chore] Toss REST API 구현 및 payment 페이지 완성
> [Chore] Toss REST API 구현 및 payment 페이지 완성

- src/components/Member/Contract/Contract3.jsx
- src/components/Member/MemberHeader.jsx
- src/components/Member/MemberMain.jsx
- src/components/Member/MemberMypage.jsx
- src/components/Member/MemberSide.jsx
- MemberMypage 예약 목록 인터페이스 변경
- MemberMain 데이터 구조 변경
> [Chore] MemberMypage 예약 목록 인터페이스 변경

- src/components/Member/Contract/InitialItemLog.js
- src/components/Member/MemberHeader.jsx
- src/components/Member/MemberInfo.jsx
- src/components/Member/MemberMain.jsx
- src/components/Member/UploadProperty.jsx
- src/components/api/MobileAuth.jsx
[Chore] MemberMain / MemberInfo 페이지 완성 및 UploadProperty 리팩토링
> [Chore] MemberMain / MemberInfo 페이지 완성 및 UploadProperty 리팩토링

- src/App.jsx
- src/components/Guest/GuestSell.jsx
- src/components/Member/ContractCheck.jsx
- src/components/Member/MemberMypage.jsx
- src/components/Member/MemberSide.jsx
- src/components/api/Toss/Success.jsx
- src/components/api/Toss/TossPayment.jsx
[Chore] 계약 조회 페이지 제작 및 전체적인 코드 리팩토링
> [Chore] 계약 조회 페이지 제작 및 전체적인 코드 리팩토링

- src/components/Member/ContractCheck.jsx
- src/components/Member/MemberInfo.jsx
- src/components/Member/MemberMain.jsx
- src/components/Member/MemberMypage.jsx
> /member css 수정

- src/components/Member/Contract/Contract2.jsx
- src/components/Member/Contract/Contract3.jsx
- src/components/Member/Contract/Contract6.jsx
- src/components/Member/MemberMypage.jsx
- 예약 취소 기능 구현
- Contract css 수정
> [Chore] /member/mypage 예약 취소 기능 구현

- src/components/Guest/GuestBook.jsx
- src/components/Guest/GuestInfo.jsx
- src/components/Guest/GuestSell.jsx
- src/components/Member/MemberMypage.jsx
- src/components/Member/UploadProperty.jsx
- src/components/api/Toss/Success.jsx
- MemerMypage 예약 내역에서 계약서 작성시 예약 내역에 남아있지 않도록 처리
- Member, Guest 전반적인 css 수정
> [Chore] MemberMypage 예약 오류 수정, CSS 수정

- src/App.jsx
- src/components/Member/Contract/Contract6.jsx
- src/components/Member/MemberMypage.jsx
- src/components/api/MobileAuth.jsx
[Chore] Contract6, QR 인증 로직 초기 구현
성공 여부 확인 전
> [Chore] Contract6, QR 인증 로직 초기 구현

- src/components/Member/MemberMypage.jsx
- 맨 첫 이미지 미리보기로 띄우기
- 클릭 시 모달에서 페이지네이션으로 전체 이미지 확인 가능
> [Chore] Image 미리보기 구현
